name: task_manager_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  get: ^4.6.6
  firebase_core: ^2.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto/Roboto-Bold.ttf
        - asset: assets/font/Roboto/Roboto-Regular.ttf
        - asset: assets/font/Roboto/Roboto-Thin.ttf
        - asset: assets/font/Roboto/Roboto-Italic.ttf
        - asset: assets/font/Roboto/Roboto-Medium.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
